#!/usr/bin/env python3
"""Regenerate lab/gallery/index.html from lab/sims/*/sim.json. Stdlib only.

Run from anywhere: python3 lab/tools/build-gallery.py
"""

import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SIMS = ROOT / "sims"
OUT = ROOT / "gallery" / "index.html"

KIND_LABEL = {"web": "interactive", "py": "python"}


def load_sims():
    sims = []
    for meta_path in sorted(SIMS.glob("*/sim.json")):
        try:
            meta = json.loads(meta_path.read_text())
        except json.JSONDecodeError as e:
            sys.exit(f"error: {meta_path.relative_to(ROOT)}: {e}")
        meta["_dir"] = meta_path.parent.name
        sims.append(meta)
    sims.sort(key=lambda m: (m.get("created", ""), m["_dir"]), reverse=True)
    return sims


def card(m):
    slug = m["_dir"]
    kind = m.get("kind", "web")
    entry = m.get("entry", "index.html")
    href = f"../sims/{slug}/{entry}"
    title = html.escape(m.get("title", slug))
    summary = html.escape(m.get("summary", ""))
    topics = "".join(f'<span class="chip">{html.escape(t)}</span>' for t in m.get("topics", []))
    family = m.get("family")
    family_html = f'<span class="chip family">{html.escape(family)}</span>' if family else ""
    status = m.get("status", "active")
    status_html = f'<span class="status">{html.escape(status)}</span>' if status != "active" else ""
    status_line = f"\n        {status_html}" if status_html else ""
    prov = m.get("provenance", {}).get("almanac")
    prov_html = f'<div class="prov">almanac: {html.escape(prov)}</div>' if prov else ""
    prov_line = f"\n      {prov_html}" if prov_html else ""
    action = (
        f'<a class="open" href="{href}">open &#8599;</a>'
        if kind == "web"
        else f'<code class="run">uv run lab/sims/{html.escape(slug)}/{html.escape(entry)}</code> '
             f'<a class="open" href="{href}">source</a>'
    )
    return f"""
    <div class="card">
      <div class="head">
        <span class="kind {kind}">{KIND_LABEL.get(kind, kind)}</span>
        <span class="date">{html.escape(m.get("created", ""))}</span>{status_line}
      </div>
      <h2>{title}</h2>
      <p>{summary}</p>
      <div class="chips">{family_html}{topics}</div>{prov_line}
      <div class="action">{action}</div>
    </div>"""


def build(sims):
    cards = "\n".join(card(m) for m in sims)
    n_web = sum(1 for m in sims if m.get("kind") == "web")
    n_py = len(sims) - n_web
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>orrery — sim gallery</title>
<style>
  body {{ margin: 0; padding: 32px 24px; background: #0b0b14; color: #c9cede; font-family: system-ui, sans-serif; }}
  header {{ max-width: 1100px; margin: 0 auto 24px; }}
  header h1 {{ font-size: 22px; margin: 0 0 4px; }}
  header p {{ color: #8b93b8; font-size: 14px; margin: 0; }}
  .grid {{ max-width: 1100px; margin: 0 auto; display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 14px; }}
  .card {{ border: 1px solid #2a2f45; border-radius: 12px; background: #050510; padding: 16px; display: flex; flex-direction: column; gap: 8px; }}
  .card h2 {{ font-size: 15px; margin: 0; }}
  .card p {{ font-size: 13px; color: #8b93b8; margin: 0; flex: 1; }}
  .head {{ display: flex; gap: 8px; align-items: center; font-size: 11px; }}
  .kind {{ padding: 2px 8px; border-radius: 999px; border: 1px solid #3a3f55; color: #8b93b8; }}
  .kind.web {{ color: #7aa2ff; border-color: #35426e; }}
  .kind.py {{ color: #86d99c; border-color: #2f5540; }}
  .date {{ color: #6a7090; font-family: ui-monospace, monospace; }}
  .status {{ color: #d9a866; }}
  .chips {{ display: flex; flex-wrap: wrap; gap: 6px; }}
  .chip {{ font-size: 11px; padding: 2px 8px; border-radius: 999px; background: #1a1f30; color: #8b93b8; }}
  .chip.family {{ color: #b39ddb; background: #221a30; }}
  .prov {{ font-size: 11px; color: #6a7090; font-family: ui-monospace, monospace; overflow-wrap: anywhere; }}
  .action {{ font-size: 13px; }}
  .action a.open {{ color: #7aa2ff; text-decoration: none; }}
  .action a.open:hover {{ text-decoration: underline; }}
  .run {{ font-size: 11px; color: #86d99c; background: #101522; padding: 2px 6px; border-radius: 6px; }}
</style>
</head>
<body>
<header>
  <h1>orrery</h1>
  <p>{len(sims)} sims &middot; {n_web} interactive &middot; {n_py} python &middot; generated by lab/tools/build-gallery.py</p>
</header>
<div class="grid">
{cards}
</div>
</body>
</html>
"""


if __name__ == "__main__":
    sims = load_sims()
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(build(sims))
    print(f"gallery/index.html: {len(sims)} sims")
